//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelHardlinks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DelHardlinks.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.Santos.
        /// </summary>
        internal static string App_Author {
            get {
                return ResourceManager.GetString("App_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        /// Usage: DelHardlinks [options] &quot;full directory path&quot;
        /// Options:
        ///	&lt;Opt_DeleteHardlinks&gt;, &lt;Opt_Str_DeleteHardlinks&gt;
        ///	&lt;Opt_DeleteJunctions&gt;, &lt;Opt_Str_DeleteJunctions&gt;
        ///	&lt;Opt_DeleteSymbLnks&gt;, &lt;Opt_Str_DeleteSymbLnks&gt;
        ///	&lt;Opt_ScanSubFolders&gt;, &lt;Opt_Str_ScanSubFolders&gt;
        ///	&lt;Opt_ScanLnkSubFolders&gt;, &lt;Opt_Str_ScanLnkSubFolders&gt;
        ///	&lt;Opt_PermanentDel&gt;, &lt;Opt_Str_PermanentDel&gt;
        ///	&lt;Opt_ShowFullPath&gt;, &lt;Opt_Str_ShowFullPath&gt;
        ///	&lt;Opt_PressKeyQuit&gt;, &lt;Opt_Str_PressKeyQuit&gt;
        ///	&lt;Opt_NotPromptForYesNo&gt;, &lt;Opt_Str_NotPromptForYesNo&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App_Help {
            get {
                return ResourceManager.GetString("App_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License: BSD (3-clause)
        ///!!! Use this tool with caution.
        ///If you don&apos;t know what it is, don&apos;t use it.
        ///Improper use can result in data loss. !!!.
        /// </summary>
        internal static string App_License {
            get {
                return ResourceManager.GetString("App_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelHardlinks.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        internal static string App_Year {
            get {
                return ResourceManager.GetString("App_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basepath is not rooted!.
        /// </summary>
        internal static string Err_BasepathIsNotRooted {
            get {
                return ResourceManager.GetString("Err_BasepathIsNotRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Directory not found).
        /// </summary>
        internal static string Err_DirNotFound {
            get {
                return ResourceManager.GetString("Err_DirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Drive not found).
        /// </summary>
        internal static string Err_DriveNotFound {
            get {
                return ResourceManager.GetString("Err_DriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (File not found).
        /// </summary>
        internal static string Err_FileNotFound {
            get {
                return ResourceManager.GetString("Err_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path!.
        /// </summary>
        internal static string Err_InvalidFilePath {
            get {
                return ResourceManager.GetString("Err_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Invalid &quot;{1}&quot; option !.
        /// </summary>
        internal static string Err_InvalidOption {
            get {
                return ResourceManager.GetString("Err_InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid system path!.
        /// </summary>
        internal static string Err_NotValidPath {
            get {
                return ResourceManager.GetString("Err_NotValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not found! .
        /// </summary>
        internal static string Err_PathNotFound {
            get {
                return ResourceManager.GetString("Err_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Path too long).
        /// </summary>
        internal static string Err_PathTooLong {
            get {
                return ResourceManager.GetString("Err_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error: Recyclebin path cannot be determined !.
        /// </summary>
        internal static string Err_RecyclebinPathCannotBeDetermined {
            get {
                return ResourceManager.GetString("Err_RecyclebinPathCannotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Security error).
        /// </summary>
        internal static string Err_SecurityError {
            get {
                return ResourceManager.GetString("Err_SecurityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unauthorized access).
        /// </summary>
        internal static string Err_UnauthorizedAccess {
            get {
                return ResourceManager.GetString("Err_UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a rooted path ! (a non-relative path).
        /// </summary>
        internal static string Err_UseRootedPath {
            get {
                return ResourceManager.GetString("Err_UseRootedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid \&quot;{arg}\&quot; option!.
        /// </summary>
        internal static string InvalidArgOption {
            get {
                return ResourceManager.GetString("InvalidArgOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted ! .
        /// </summary>
        internal static string Msg_Aborted {
            get {
                return ResourceManager.GetString("Msg_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused...Press &lt;spacebar&gt; key to continue .
        /// </summary>
        internal static string Msg_PressSpacebarToContinue {
            get {
                return ResourceManager.GetString("Msg_PressSpacebarToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving file data....
        /// </summary>
        internal static string Msg_RetrievingFileData {
            get {
                return ResourceManager.GetString("Msg_RetrievingFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving subfolder data....
        /// </summary>
        internal static string Msg_RetrievingSubfolderData {
            get {
                return ResourceManager.GetString("Msg_RetrievingSubfolderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -dH.
        /// </summary>
        internal static string Opt_DeleteHardlinks {
            get {
                return ResourceManager.GetString("Opt_DeleteHardlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -dJ.
        /// </summary>
        internal static string Opt_DeleteJunctions {
            get {
                return ResourceManager.GetString("Opt_DeleteJunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -dK.
        /// </summary>
        internal static string Opt_DeleteSymbLnks {
            get {
                return ResourceManager.GetString("Opt_DeleteSymbLnks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -l:.
        /// </summary>
        internal static string Opt_Log {
            get {
                return ResourceManager.GetString("Opt_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -u:.
        /// </summary>
        internal static string Opt_MaxDiskUsage {
            get {
                return ResourceManager.GetString("Opt_MaxDiskUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -y.
        /// </summary>
        internal static string Opt_NotPromptForYesNo {
            get {
                return ResourceManager.GetString("Opt_NotPromptForYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p.
        /// </summary>
        internal static string Opt_PermanentDel {
            get {
                return ResourceManager.GetString("Opt_PermanentDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -m.
        /// </summary>
        internal static string Opt_PressKeyQuit {
            get {
                return ResourceManager.GetString("Opt_PressKeyQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -sL.
        /// </summary>
        internal static string Opt_ScanLnkSubFolders {
            get {
                return ResourceManager.GetString("Opt_ScanLnkSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -s.
        /// </summary>
        internal static string Opt_ScanSubFolders {
            get {
                return ResourceManager.GetString("Opt_ScanSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -o.
        /// </summary>
        internal static string Opt_ShowFullPath {
            get {
                return ResourceManager.GetString("Opt_ShowFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Delete hardlinks.
        /// </summary>
        internal static string Opt_Str_DeleteHardlinks {
            get {
                return ResourceManager.GetString("Opt_Str_DeleteHardlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Delete all junctions.
        /// </summary>
        internal static string Opt_Str_DeleteJunctions {
            get {
                return ResourceManager.GetString("Opt_Str_DeleteJunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Delete all symbolic links.
        /// </summary>
        internal static string Opt_Str_DeleteSymbLnks {
            get {
                return ResourceManager.GetString("Opt_Str_DeleteSymbLnks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Log file:.
        /// </summary>
        internal static string Opt_Str_Log {
            get {
                return ResourceManager.GetString("Opt_Str_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Maximum disk usage:.
        /// </summary>
        internal static string Opt_Str_MaxDiskUsage {
            get {
                return ResourceManager.GetString("Opt_Str_MaxDiskUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Assume &quot;yes&quot; to every deletion.
        /// </summary>
        internal static string Opt_Str_NotPromptForYesNo {
            get {
                return ResourceManager.GetString("Opt_Str_NotPromptForYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Permanent deletion.
        /// </summary>
        internal static string Opt_Str_PermanentDel {
            get {
                return ResourceManager.GetString("Opt_Str_PermanentDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -User iteration &lt;Press a key to halt before quitting&gt;.
        /// </summary>
        internal static string Opt_Str_PressKeyQuit {
            get {
                return ResourceManager.GetString("Opt_Str_PressKeyQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Scan into linked subfolders.
        /// </summary>
        internal static string Opt_Str_ScanLnkSubFolders {
            get {
                return ResourceManager.GetString("Opt_Str_ScanLnkSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Scan into subfolders.
        /// </summary>
        internal static string Opt_Str_ScanSubFolders {
            get {
                return ResourceManager.GetString("Opt_Str_ScanSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Show full path.
        /// </summary>
        internal static string Opt_Str_ShowFullPath {
            get {
                return ResourceManager.GetString("Opt_Str_ShowFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string Str_Dir {
            get {
                return ResourceManager.GetString("Str_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [H{0} J{1} S{2}, F{3}/{4}, E:{5}].
        /// </summary>
        internal static string Str_Info {
            get {
                return ResourceManager.GetString("Str_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file.
        /// </summary>
        internal static string Str_LogFile {
            get {
                return ResourceManager.GetString("Str_LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Str_Message {
            get {
                return ResourceManager.GetString("Str_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :\$RECYCLE.BIN\.
        /// </summary>
        internal static string Str_RECYCLEBIN {
            get {
                return ResourceManager.GetString("Str_RECYCLEBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown process is performing too many I/O operations on the storage device.  Do you want to &lt;c&gt;ontinue with limited resources or &lt;a&gt;bort operation ?.
        /// </summary>
        internal static string Warn_DriveOverload {
            get {
                return ResourceManager.GetString("Warn_DriveOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program instance is already running! .
        /// </summary>
        internal static string Warn_InstanceAlreadyRunning {
            get {
                return ResourceManager.GetString("Warn_InstanceAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary file cannot be permanently deleted !.
        /// </summary>
        internal static string Warn_TemporaryFileCannotBePermanentlyDeleted {
            get {
                return ResourceManager.GetString("Warn_TemporaryFileCannotBePermanentlyDeleted", resourceCulture);
            }
        }
    }
}
